### ISSUE TITLE
Would be more appropriately named `max absolute error`

### ISSUE THREAD

**Issue by wknoben** [acebulsk/doc-paper#1]
https://github.com/acebulsk/doc-paper/blob/6297b5e7fa3284ba3faee1e40f65e4bcda95b26d/doc-paper-supplement.qmd#L312

**Comment by acebulsk** [comment]
I think this is still Max Error.. the which.max function finds the index for the largest absolute diff then we return the raw diff value (could be pos. or neg.) at that index.
